conf:
  # Configuration of email notification
  notify:
    email:


  # Configure local folder for sql and temporary data store for notification
  localfs:
    xls_path: "/home/gwcda_code/output"
    sql_path: "/home/gwcda_code/conf"

  #Secret manager details to fetch postgres creds
  secrets:
    secret_name: ""
    secret_region: ""

  #Postgres connection details to execute the select queries
  postgresJDBC:
    jdbcUrl: ""
    jdbcDatabase: ""
    jdbcSchema: "claims_merged"
    postgres_user: "gw_postgres_usr"
    postgres_pwd: "gw_postgres_usr_pwd"

  gw_s3_con:
    bucketName: ""
    accessKey: "gw_secret_key"
    secretKey: "gw_access_key"